### ISSUE TITLE
add text to rhf pipeline notebook

### ISSUE THREAD

**Issue by rfl-urbaniak** [BasisResearch/collab-creatures#53]
- visibility:  I had been thinking of this as more of a meta-parameter, but now it's plotted with a coefficient similar to the derived predictor terms in the value function (proximity and trace). How are you interpreting the coefficient on visibility?

**Comment by emackev** [comment]
Will be closed by https://github.com/BasisResearch/collab-creatures/pull/66

**Comment by rfl-urbaniak** [comment]
done
